name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '**.zig'
    - '**.zon'
    - '**.c'
    - '**.h'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build

      - name: Test
        run: |
          zig build test -Doptimize=Debug
          zig build test -Doptimize=ReleaseFast
